## Linear Regression

In [5]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv(r"c:\Users\hp\Downloads\archive (8)\loan_data_set.csv")
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [7]:
# data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [8]:
# simple Linear regression --> y = mx+c 
#  one input or one output

In [9]:
df.dropna(axis=0, inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 480 entries, 1 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            480 non-null    object
 1   Gender             480 non-null    object
 2   Married            480 non-null    object
 3   Dependents         480 non-null    object
 4   Education          480 non-null    object
 5   Self_Employed      480 non-null    object
 6   ApplicantIncome    480 non-null    int64
 7   CoapplicantIncome  480 non-null    float64
 8   LoanAmount         480 non-null    float64
 9   Loan_Amount_Term   480 non-null    float64
 10  Credit_History     480 non-null    float64
 11  Property_Area      480 non-null    object
 12  Loan_Status        480 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 52.5+ KB

In [11]:
# x or input variable
df["ApplicantIncome"]
# x = df[["ApplicantIncome"]]

1      4583
2      3000
3      2583
4      6000
5      5417
       ...
609    2900
610    4106
611    8072
612    7583
613    4583
Name: ApplicantIncome, Length: 480, dtype: int64

In [12]:
# y or target variable
df["LoanAmount"]

# y =df[["LoanAmount"]]

1      128.0
2       66.0
3      120.0
4      141.0
5      267.0
       ...
609     71.0
610     40.0
611    253.0
612    187.0
613    133.0
Name: LoanAmount, Length: 480, dtype: float64

In [13]:
# split the for model creations in training and testing
from sklearn.model_selection import  train_test_split
x_train ,x_test, y_train, y_test = train_test_split(df[["ApplicantIncome"]],df[["LoanAmount"]],test_size=.2, random_state=3)

In [14]:
x_train

     ApplicantIncome
41              1800
462             3015
485             1958
164             9323
207             3975
..               ...
563             5800
169             8000
316             3717
195             3125
464             4166

[384 rows x 1 columns]

In [15]:
x_test

     ApplicantIncome
37              3667
140             5042
85              2366
420             5829
384             4566
..               ...
315             3399
32              4692
224             6250
481             3095
489             2435

[96 rows x 1 columns]

In [16]:
# model implement linear regression
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [17]:
# train the model to find the cofficient and intercept (m, c)
model.fit(x_train,y_train)

LinearRegression()

In [18]:
model.coef_

array([[0.00765988]])

In [19]:
model.intercept_

array([103.88294744])

In [20]:
# y = 0.006X + 110
y_predict = model.predict(x_test)
y_predict

array([[131.97171304],
       [142.50404266],
       [122.00621426],
       [148.53236514],
       [138.85794164],
       [147.7433979 ],
       [164.76364256],
       [243.02459651],
       [128.24135339],
       [180.48170828],
       [123.08625679],
       [146.13482392],
       [116.65962075],
       [151.75717297],
       [171.28219711],
       [141.54655815],
       [123.79862526],
       [149.25239349],
       [141.10994521],
       [230.46239973],
       [157.11908623],
       [191.33575269],
       [128.61668732],
       [127.33748801],
       [216.35290798],
       [178.20672509],
       [124.30417708],
       [121.01809024],
       [118.2452151 ],
       [132.79897966],
       [215.58692038],
       [139.24093545],
       [162.55759825],
       [130.7691125 ],
       [176.71304925],
       [138.98815954],
       [140.97972732],
       [123.10923641],
       [137.4638442 ],
       [122.90241976],
       [131.36658283],
       [121.56960132],
       [133.50368826],
       [132.04065193],
       [137.07319052],
       [150.57755205],
       [122.87178026],
       [139.16433669],
       [123.23179443],
       [128.95372187],
       [149.84220395],
       [141.31676187],
       [149.84220395],
       [136.72849609],
       [218.77342883],
       [128.13411513],
       [176.68240975],
       [138.98815954],
       [124.76376965],
       [134.43053327],
       [167.71269485],
       [126.05828871],
       [128.74690521],
       [132.60748276],
       [133.44240925],
       [403.7441165 ],
       [164.64874442],
       [132.25512846],
       [224.59493465],
       [145.17733941],
       [122.45814695],
       [119.54739404],
       [137.64768122],
       [151.75717297],
       [105.03192886],
       [129.97248539],
       [153.03637227],
       [142.18232786],
       [132.60748276],
       [160.88008538],
       [119.14908048],
       [144.2198549 ],
       [163.53040251],
       [127.42174665],
       [136.8204146 ],
       [145.76714987],
       [122.96369877],
       [128.45582992],
       [137.15744915],
       [123.62244811],
       [128.141775  ],
       [129.91886625],
       [139.82308603],
       [151.75717297],
       [127.59026392],
       [122.53474571]])

In [21]:
y_test

     LoanAmount
37        144.0
140       185.0
85        136.0
420       138.0
384       100.0
..          ...
315       111.0
32        106.0
224       128.0
481       113.0
489        75.0

[96 rows x 1 columns]

In [22]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
mean_absolute_error(y_test, y_predict)

np.float64(48.765371958066225)

In [23]:
# accuracy check
r2_score(y_test, y_predict)

-0.026403910468808967

### MULTI- LINEAR REGRESSION

In [24]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [25]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,480.000000,480.000000,480.000000,480.000000,480.000000
mean,5364.231250,1581.093583,144.735417,342.050000,0.854167
std,5668.251251,2617.692267,80.508164,65.212401,0.353307
min,150.000000,0.000000,9.000000,36.000000,0.000000
25%,2898.750000,0.000000,100.000000,360.000000,1.000000
50%,3859.000000,1084.500000,128.000000,360.000000,1.000000
75%,5852.500000,2253.250000,170.000000,360.000000,1.000000
max,81000.000000,33837.000000,600.000000,480.000000,1.000000

In [26]:
df.dropna(inplace= True)

In [27]:
df[["ApplicantIncome","CoapplicantIncome","LoanAmount","Loan_Amount_Term","Credit_History"]]

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
1,4583,1508.0,128.0,360.0,1.0
2,3000,0.0,66.0,360.0,1.0
3,2583,2358.0,120.0,360.0,1.0
4,6000,0.0,141.0,360.0,1.0
5,5417,4196.0,267.0,360.0,1.0
...,...,...,...,...,...
609,2900,0.0,71.0,360.0,1.0
610,4106,0.0,40.0,180.0,1.0
611,8072,240.0,253.0,360.0,1.0
612,7583,0.0,187.0,360.0,1.0
613,4583,0.0,133.0,360.0,0.0

In [28]:
x = df[["ApplicantIncome","CoapplicantIncome","Loan_Amount_Term","Credit_History"]]
x

     ApplicantIncome  CoapplicantIncome  Loan_Amount_Term  Credit_History
1               4583             1508.0             360.0             1.0
2               3000                0.0             360.0             1.0
3               2583             2358.0             360.0             1.0
4               6000                0.0             360.0             1.0
5               5417             4196.0             360.0             1.0
..               ...                ...               ...             ...
609             2900                0.0             360.0             1.0
610             4106                0.0             180.0             1.0
611             8072              240.0             360.0             1.0
612             7583                0.0             360.0             1.0
613             4583                0.0             360.0             0.0

[480 rows x 4 columns]

In [29]:
y = df[["LoanAmount"]]
y

     LoanAmount
1         128.0
2          66.0
3         120.0
4         141.0
5         267.0
..          ...
609        71.0
610        40.0
611       253.0
612       187.0
613       133.0

[480 rows x 1 columns]

In [30]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=65)
model2 = LinearRegression()
model2.fit(x_train, y_train)

LinearRegression()

In [31]:
model2.coef_

array([[ 0.00771078,  0.00562096,  0.05675914, -0.8361798 ]])

In [32]:
model2.intercept_

array([74.92518009])

In [33]:
# predict
y_pred = model2.predict(x_test)
mean_squared_error(y_test,y_pred)
r2_score(y_test,y_pred)

0.18327176016515767

In [34]:
model2.score(x_test,y_test)

0.18327176016515767

In [35]:
model2.score(x_test,y_test)

0.18327176016515767

In [36]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [37]:
# !pip install streamlit

In [38]:
# from sklearn import svm
# from sklearn import datasets

# iris = datasets.load_iris()
# X, y = iris.data, iris.target

# clf = svm.SVC()
# clf.fit(X, y)  

# ##########################
# # SAVE-LOAD using pickle #
# ##########################
# import pickle

# # save
# with open('model.pkl','wb') as f:
#     pickle.dump(clf,f)

# # load
# with open('model.pkl', 'rb') as f:
#     clf2 = pickle.load(f)

# clf2.predict(X[0:1])

In [39]:
import pickle
# save
with open('linear_regression_model.pkl','wb') as f:
    pickle.dump(model2,f)

In [40]:
# Regression predictions

import pickle
# save
with open('linear_regression_model.pkl','wb') as f:
    pickle.dump(model2,f)
import streamlit as st
import pandas as pd
import numpy as np
import pickle

# Load the trained regression model
with open("linear_regression_model.pkl", "rb") as file:
    model = pickle.load(file)

st.title("Loan Amount Prediction")
st.write("Enter the required details to predict the loan amount.")

# Input fields for user
applicant_income = st.number_input("Applicant Income", min_value=0)
coapplicant_income = st.number_input("Coapplicant Income", min_value=0)
loan_amount_term = st.number_input("Loan Amount Term", min_value=0)
credit_history = st.selectbox("Credit History", [0, 1])

# Predict button
if st.button("Predict Loan Amount"):
    # Create a DataFrame with user input
    input_data = pd.DataFrame(
        [[applicant_income, coapplicant_income, loan_amount_term, credit_history]],
        columns=["ApplicantIncome", "CoapplicantIncome", "Loan_Amount_Term", "Credit_History"]
    )
    
    # Predict loan amount
    predicted_loan_amount = model.predict(input_data)[0]
    
    st.success(f"Predicted Loan Amount: {predicted_loan_amount:.2f}")

st.write("Upload a dataset for batch predictions")
uploaded_file = st.file_uploader("Upload CSV", type=["csv"])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    predictions = model.predict(df)
    df["Predicted Loan Amount"] = predictions
    st.write(df)
    df.to_csv("predicted_loans.csv", index=False)
    st.download_button("Download Predictions", "predicted_loans.csv")

# streamlit run streamlit_loan.py

2025-02-06 15:45:13.015 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:15.932
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run c:\ProgramData\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2025-02-06 15:45:15.943 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:15.947 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:15.948 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:15.965 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:15.975 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:15.977 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:15.979 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:15.982 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:15.988 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:15.990 Session state does not function when running a script without `streamlit run`
2025-02-06 15:45:15.992 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:15.997 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.005 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.008 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.009 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.012 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.015 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.017 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.023 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.025 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.027 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.028 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.048 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.066 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.082 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.090 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.100 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.107 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.122 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.125 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.127 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.130 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.133 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.138 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.140 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.142 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.145 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:16.147 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

# Logistic regression
y --> categorical data

In [41]:
df = pd.read_csv("loan_data_set.csv")
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [42]:
from sklearn.preprocessing import  LabelEncoder

l = LabelEncoder()
y  = l.fit_transform(df["Loan_Status"])
y = pd.DataFrame(y)

df["Loan_Status"] =  y

In [43]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,1
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,0
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,1
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,1
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,1
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,1
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,1
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,1
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,0

In [44]:
df.drop("Loan_ID",axis=1, inplace=True)

In [45]:
for i in df.columns:
    if df[i].dtype =="O":
        print(i)
        y  = l.fit_transform(df[i])
        df[i] =  pd.DataFrame(y)

df

Gender
Married
Dependents
Education
Self_Employed
Property_Area

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1,0,0,0,0,5849,0.0,NaN,360.0,1.0,2,1
1,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0,0
2,1,1,0,0,1,3000,0.0,66.0,360.0,1.0,2,1
3,1,1,0,1,0,2583,2358.0,120.0,360.0,1.0,2,1
4,1,0,0,0,0,6000,0.0,141.0,360.0,1.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,0,0,2900,0.0,71.0,360.0,1.0,0,1
610,1,1,3,0,0,4106,0.0,40.0,180.0,1.0,0,1
611,1,1,1,0,0,8072,240.0,253.0,360.0,1.0,2,1
612,1,1,2,0,0,7583,0.0,187.0,360.0,1.0,2,1
613,0,0,0,0,1,4583,0.0,133.0,360.0,0.0,1,0

In [46]:
df.dropna(inplace=True)

In [47]:
df.dtypes

Gender                 int64
Married                int64
Dependents             int64
Education              int64
Self_Employed          int64
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area          int64
Loan_Status            int64
dtype: object

In [48]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0,0
2,1,1,0,0,1,3000,0.0,66.0,360.0,1.0,2,1
3,1,1,0,1,0,2583,2358.0,120.0,360.0,1.0,2,1
4,1,0,0,0,0,6000,0.0,141.0,360.0,1.0,2,1
5,1,1,2,0,1,5417,4196.0,267.0,360.0,1.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,0,0,2900,0.0,71.0,360.0,1.0,0,1
610,1,1,3,0,0,4106,0.0,40.0,180.0,1.0,0,1
611,1,1,1,0,0,8072,240.0,253.0,360.0,1.0,2,1
612,1,1,2,0,0,7583,0.0,187.0,360.0,1.0,2,1
613,0,0,0,0,1,4583,0.0,133.0,360.0,0.0,1,0

In [ ]:
# classifications  y --> categorical data
# regression  y --> continuous data
y = df["LoanAmount"]
y

x = df.drop("LoanAmount",axis=1)
x

x = df[["ApplicantIncome","CoapplicantIncome","Loan_Amount_Term","Loan_Status","Credit_History"]]
x

,ApplicantIncome,CoapplicantIncome,Loan_Amount_Term,LoanAmount,Credit_History
1,4583,1508.0,360.0,128.0,1.0
2,3000,0.0,360.0,66.0,1.0
3,2583,2358.0,360.0,120.0,1.0
4,6000,0.0,360.0,141.0,1.0
5,5417,4196.0,360.0,267.0,1.0
...,...,...,...,...,...
609,2900,0.0,360.0,71.0,1.0
610,4106,0.0,180.0,40.0,1.0
611,8072,240.0,360.0,253.0,1.0
612,7583,0.0,360.0,187.0,1.0
613,4583,0.0,360.0,133.0,0.0

In [ ]:
from sklearn.linear_model import LinearRegression

x_train,x_test,y_train, y_test = train_test_split(x,y , test_size=.2, random_state=30)

# model obj
lr = LinearRegression()
lr.fit(x_train, y_train)

LogisticRegression(solver='liblinear')

In [51]:
lr.score(x_test,y_test)

0.7924528301886793

In [52]:
import pandas as pd

In [ ]:
input_data = pd.DataFrame(
        [[10000,20000,24, 10000,0]],
        columns=["ApplicantIncome","CoapplicantIncome","Loan_Amount_Term","LoanStatus","Credit_History"]
    )
input_data

,ApplicantIncome,CoapplicantIncome,Loan_Amount_Term,LoanAmount,Credit_History
0,10000,20000,24,10000,0

In [54]:
lr.predict(input_data)

array([0])

In [55]:
y_predict = lr.predict(x_test)

In [68]:
import pickle

with open("model1.pkl","wb") as f:
    pickle.dump(lr,f)

In [ ]:
import pickle
# save
with open('linear_regression_model.pkl','wb') as f:
    pickle.dump(lr,f)

In [ ]:
import streamlit as st
import pandas as pd
import numpy as np
import pickle

# Load the trained regression model
with open("linear_regression_model.pkl", "rb") as file:
    model = pickle.load(file)

st.title("Loan Amount Prediction")
st.write("Enter the required details to predict the loan amount.")

# Input fields for user
applicant_income = st.number_input("Applicant Income", min_value=0)
coapplicant_income = st.number_input("Coapplicant Income", min_value=0)
loan_amount_term = st.number_input("Loan Status ", min_value=0)
credit_history = st.selectbox("Credit History", [0, 1])

# Predict button
if st.button("Predict Loan Amount"):
    # Create a DataFrame with user input
    input_data = pd.DataFrame(
        [[applicant_income, coapplicant_income, loan_amount_term, credit_history]],
        columns=["ApplicantIncome", "CoapplicantIncome", "LoanStatus", "Credit_History"]
    )
    
    # Predict loan amount
    predicted_loan_amount = model.predict(input_data)[0]
    
    st.success(f"Predicted Loan Amount: {predicted_loan_amount}")

st.write("Upload a dataset for batch predictions")
uploaded_file = st.file_uploader("Upload CSV", type=["csv"])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    predictions = model.predict(df)
    df["Predicted Loan Amount"] = predictions
    st.write(df)
    df.to_csv("predicted_loans.csv", index=False)
    st.download_button("Download Predictions", "predicted_loans.csv")
# run
# python -m streamlit run streamlit_loan.py

2025-02-06 15:45:19.529 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.531 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.538 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.541 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.542 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.546 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.550 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.556 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.559 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.561 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.563 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.565 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.574 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.579 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.592 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.596 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.610 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.624 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.626 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.630 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.648 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.659 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.679 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.688 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.697 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.709 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.710 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.713 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.715 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.716 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.723 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.726 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.730 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.738 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.798 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.807 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.814 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.816 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.823 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-06 15:45:19.830 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.